### ISSUE TITLE
NewRelicを導入してスリープしないようにする

### ISSUE THREAD

**Issue by ya-s-u** [hyde2able/FireCommits#1]
herokuは１時間アクセスがないと寝ちゃうのでその対策とかあるといいかも！

**Comment by hyde2able** [comment]
cron とかで一時間に一回アクセスするとかって感じでやれば大丈夫ですかね？

**Comment by pokohide** [comment]
NewRelic導入しました！ありがとうございます！
とりあえずアップしてみたけど、同時アクセスとかあって、それで同時にDSにプッシュされちゃうとかバグ的なの見つかって勉強になりますw

issue機能使うの初めてです。導入完了したから閉じちゃっていいのかな。。
